### PR TITLE
Minor change to readme

### PR DESCRIPTION
**Pull request by oscrx**

### CODE REVIEW

**Review by cbachhuber — APPROVED** [review]
Just wanted to open a PR to fix exactly this :smile:

**Comment by oscrx** [comment]
Is this going to get merged?

**Comment by graysky2** [comment]
Can you squash/rebase into 1

**Comment by oscrx** [comment]
So i tried to do this, but for some reason I deleted the fork in the meantime. I forked the repo again and made the change, but Github no longer links to it from this pull request.
I think there are a few options though.

1. I create another pull request from [the new repo](https://github.com/oscrx/xscreensaver-aerial)
2. Use the squash and merge button Github (hopefully) offers Schermafbeelding 2020-02-25 om 07 50 13
3. Make the change yourself, it's not a big change.

**Pull request closed without merging**
